services:
  - type: web
    name: inventoryapp-api
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: inventorydb
          property: connectionString

databases:
  - name: inventorydb
    databaseName: inventorydb
    user: app
    plan: free
